"""Initial database schema

Revision ID: 0001_initial
Revises: 
Create Date: 2024-08-09 20:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'MANAGER', name='adminrole'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('actor_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('actor_role', sa.VARCHAR(length=30), nullable=False),
    sa.Column('action', sa.VARCHAR(length=100), nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('entity_id', sa.BIGINT(), nullable=True),
    sa.Column('old_data', sa.JSON(), nullable=True),
    sa.Column('new_data', sa.JSON(), nullable=True),
    sa.Column('ip_or_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('recipient_telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('recipient_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.BIGINT(), nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_is_sent'), 'notifications', ['is_sent'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('telegram_id', sa.BIGINT(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=32), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'BLOCKED', name='userstatus'), nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('age BETWEEN 13 AND 120', name='users_age_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('balance_transactions',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('TOPUP', 'PURCHASE', 'REFUND', 'MANUAL_CREDIT', 'MANUAL_DEBIT', name='balancetxtype'), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('balance_before', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.BIGINT(), nullable=True),
    sa.Column('created_by_admin_id', sa.BIGINT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_number', sa.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_ADMIN', 'APPROVED', 'PACKING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'REJECTED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('delivery_address', sa.TEXT(), nullable=False),
    sa.Column('delivery_deadline', sa.DateTime(), nullable=True),
    sa.Column('assigned_admin_id', sa.BIGINT(), nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_amount > 0', name='orders_total_amount_check'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('category_id', sa.BIGINT(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=300), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('image_file_id', sa.TEXT(), nullable=True),
    sa.Column('image_url', sa.TEXT(), nullable=True),
    sa.Column('cost_price_per_gram', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('sale_price_per_gram', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('stock_grams', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('low_stock_threshold_grams', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('last_low_stock_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_price_per_gram >= 0', name='products_cost_price_check'),
    sa.CheckConstraint('sale_price_per_gram >= 0', name='products_sale_price_check'),
    sa.CheckConstraint('stock_grams >= 0', name='products_stock_grams_check'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('topups',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=80), nullable=False),
    sa.Column('receipt_file_id', sa.TEXT(), nullable=True),
    sa.Column('external_transaction_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='topupstatus'), nullable=False),
    sa.Column('admin_id', sa.BIGINT(), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='topups_amount_check'),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_transaction_id')
    )
    op.create_index(op.f('ix_topups_status'), 'topups', ['status'], unique=False)
    op.create_table('delivery_events',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_by_admin_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('product_name_snapshot', sa.VARCHAR(length=255), nullable=False),
    sa.Column('grams', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('unit_price_per_gram', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('cost_price_per_gram_snapshot', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=18, scale=2), nullable=False),
    sa.CheckConstraint('grams > 0', name='order_items_grams_check'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('product_id', sa.BIGINT(), nullable=False),
    sa.Column('type', sa.Enum('PURCHASE_IN', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'SALE_OUT', 'RETURN_IN', 'DAMAGE_OUT', name='stockmovementtype'), nullable=False),
    sa.Column('grams', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('stock_before', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('stock_after', sa.NUMERIC(precision=18, scale=3), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('reference_id', sa.BIGINT(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('created_by_admin_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('grams > 0', name='stock_movements_grams_check'),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stock_product_created', 'stock_movements', ['product_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_product_created', table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_table('order_items')
    op.drop_table('delivery_events')
    op.drop_index(op.f('ix_topups_status'), table_name='topups')
    op.drop_table('topups')
    op.drop_table('products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('balance_transactions')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_notifications_is_sent'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('categories')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    op.drop_table('admins')
    
    # Drop ENUM types
    sa.Enum(name='userstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='adminrole').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='topupstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='orderstatus').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='stockmovementtype').drop(op.get_bind(), checkfirst=False)
    sa.Enum(name='balancetxtype').drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###