


"""add language_code to models

Revision ID: 9e2265d6359b
Revises: 0001_initial
Create Date: 2024-08-10 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2265d6359b'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('language_code', sa.VARCHAR(length=2), server_default='uz', nullable=False))
    op.add_column('users', sa.Column('language_code', sa.VARCHAR(length=2), server_default='uz', nullable=False))
    op.alter_column('admins', 'language_code', server_default=None)
    op.alter_column('users', 'language_code', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language_code')
    op.drop_column('admins', 'language_code')
    # ### end Alembic commands ###