# A generic alembic configuration file.

[alembic]
# path to migration scripts
script_location = migrations

# template for migration file names, e.g. "%%(rev)s_%%(slug)s"
# The default is "%%(rev)s_%%(slug)s"
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone for dates in file names
# default: Don't apply any timezone conversion
# timezone =

# title for migration file "slug"
# default: Use the first 40 characters of the migration message
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'check' command, regardless of whether or not
# migrations are already present.
# check_migrations_on_stale_env = false

# Semicolon-separated list of supported database dialects
# 'dialect_name[+driver_name]'
# dialects = postgresql, mssql, sqlite

# revision name generation options
[revision]
# format for autogenerated revision identifiers
# "short" -> a short random string
# "hex" -> a hex string
# "sequential" -> sequential integers
# identifier_format = short

# autogenerate options
# "unique" -> only one autogenerate revision can be the "head"
# "none" -> no restriction on autogenerated revisions
# depends_on_past = none

# Post-write hooks are Python functions that are run after a new revision
# script is generated.
[post_write_hooks]
# hook_name = dotted.path:to.hook(revision, options)

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
