# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
# nc (netcat) is used in the docker-compose command to check for DB readiness
RUN apt-get update && apt-get install -y --no-install-recommends netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Install poetry
RUN pip install poetry

# Copy only the files necessary for installing dependencies
COPY pyproject.toml poetry.lock* ./

# Install dependencies
# --no-root is important to avoid installing the project itself as editablRUN poetry config virtualenvs.create false && poetry install --no-dev --no-interaction --no-ansi --no-root

# Copy the rest of the application's source code
COPY . .

# The command to run the application is in docker-compose.yml
# This allows for more flexibility, like running migrations before starting the app.
# CMD ["poetry", "run", "python", "-m", "shopim"]
x

